//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Layouts {
    
    
    public partial class MPInterna {
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liAdministrador;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liGerente;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liAdmGerente;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liGerenteAdm;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liPessoal;
        
        protected global::System.Web.UI.WebControls.Label lblUsuario;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liManualDesenvolvedor;
        
        protected global::System.Web.UI.WebControls.ContentPlaceHolder ContentPlaceHolder4;
    }
}
