//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages {
    
    
    public partial class pgAlterarSenha {
        
        protected global::System.Web.UI.WebControls.Panel panelAlterarSenha;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.TextBox txtSenhaAntiga;
        
        protected global::System.Web.UI.WebControls.TextBox txtSenhaNova;
        
        protected global::System.Web.UI.WebControls.TextBox txtConfirmacaoNovaSenha;
        
        protected global::System.Web.UI.WebControls.Button btnAlterar;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
    }
}
