//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages {
    
    
    public partial class pgCargo {
        
        protected global::System.Web.UI.WebControls.Panel panelCargo;
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.TextBox txtNomeCargo;
        
        protected global::System.Web.UI.WebControls.TextBox txtCargaHoraria;
        
        protected global::System.Web.UI.WebControls.Button btnSalvar;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
        protected global::System.Web.UI.WebControls.Panel panelListaCargo;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltro;
        
        protected global::System.Web.UI.WebControls.TextBox txtFiltrar;
        
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        
        protected global::System.Web.UI.WebControls.GridView gvCargos;
    }
}
