//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages.Gerente {
    
    
    public partial class pgFrequenciaFuncionario {
        
        protected global::System.Web.UI.WebControls.Panel panelListaPontos;
        
        protected global::System.Web.UI.WebControls.Label lblMensagemPonto;
        
        protected global::System.Web.UI.WebControls.GridView gvListaPontos;
        
        protected global::System.Web.UI.WebControls.Button btnVoltar;
        
        protected global::System.Web.UI.WebControls.Panel panelListaFrequencia;
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlFuncionarios;
        
        protected global::System.Web.UI.WebControls.TextBox txtDataInicial;
        
        protected global::System.Web.UI.WebControls.TextBox txtDataFinal;
        
        protected global::System.Web.UI.WebControls.Button btnMostrar;
        
        protected global::System.Web.UI.WebControls.Button btnRelatorio;
        
        protected global::System.Web.UI.WebControls.GridView gvFrequencia;
    }
}
