//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages {
    
    
    public partial class pgFuncionario {
        
        protected global::System.Web.UI.WebControls.Panel panelFuncionario;
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.TextBox txtNome;
        
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtCpf;
        
        protected global::System.Web.UI.WebControls.TextBox txtDataNascimento;
        
        protected global::System.Web.UI.WebControls.TextBox txtMatricula;
        
        protected global::System.Web.UI.WebControls.TextBox txtDataAdmissao;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlCargo;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlSetor;
        
        protected global::System.Web.UI.WebControls.TextBox txtSenha;
        
        protected global::System.Web.UI.WebControls.TextBox txtConfimarSenha;
        
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divAdministrador;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlAdministrador;
        
        protected global::System.Web.UI.WebControls.Button btnSalvar;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
        protected global::System.Web.UI.WebControls.Panel panelListaFuncionarios;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltro;
        
        protected global::System.Web.UI.WebControls.TextBox txtFiltrar;
        
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        
        protected global::System.Web.UI.WebControls.GridView gvFuncionarios;
    }
}
