//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages {
    
    
    public partial class pgAutorizarJustificativa {
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.Panel panelJustificativasPendentes;
        
        protected global::System.Web.UI.WebControls.GridView gvJustificativas;
        
        protected global::System.Web.UI.WebControls.Panel panelJustificativasAutorizadas;
        
        protected global::System.Web.UI.WebControls.GridView gvJustificativasRegional;
    }
}
