//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages {
    
    
    public partial class pgJustificativa {
        
        protected global::System.Web.UI.WebControls.Panel panelListaFrequencia;
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.TextBox txtDataInicial;
        
        protected global::System.Web.UI.WebControls.TextBox txtDataFinal;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlMotivo;
        
        protected global::System.Web.UI.WebControls.FileUpload fileComprovante;
        
        protected global::System.Web.UI.WebControls.TextBox txtDescricao;
        
        protected global::System.Web.UI.WebControls.Button btnSalvar;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
        
        protected global::System.Web.UI.WebControls.Panel panelListaFuncionarios;
        
        protected global::System.Web.UI.WebControls.GridView gvJustificativas;
    }
}
