//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages {
    
    
    public partial class pgLogin {
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.TextBox txtMatricula;
        
        protected global::System.Web.UI.WebControls.TextBox txtSenha;
        
        protected global::System.Web.UI.WebControls.Button btnLogar;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
    }
}
