//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao.Pages.Gerente {
    
    
    public partial class pgRelatorioFrequencia {
        
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.Label lblFuncionario;
        
        protected global::System.Web.UI.WebControls.Label lblInicioPeriodo;
        
        protected global::System.Web.UI.WebControls.Label lblFimPeriodo;
        
        protected global::System.Web.UI.WebControls.Label lblDiasUteis;
        
        protected global::System.Web.UI.WebControls.Label lblHorasTrabalhar;
        
        protected global::System.Web.UI.WebControls.Label lblHorasTrabalhadas;
        
        protected global::System.Web.UI.WebControls.Label lblHorasTrabalhadasSabado;
        
        protected global::System.Web.UI.WebControls.Label lblHorasTrabalhadasDomingo;
        
        protected global::System.Web.UI.WebControls.Label lblFaltas;
        
        protected global::System.Web.UI.WebControls.Label lblFaltasJustificadas;
        
        protected global::System.Web.UI.WebControls.Label lblIncompletos;
        
        protected global::System.Web.UI.WebControls.Label lblIncompletosJustificado;
        
        protected global::System.Web.UI.WebControls.Button btnImprimir;
    }
}
