//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apresentacao {
    
    
    public partial class pgFrequencia {
        
        protected global::System.Web.UI.WebControls.HiddenField hfId;
        
        protected global::System.Web.UI.WebControls.Label lblMensagem;
        
        protected global::System.Web.UI.WebControls.Panel panelMatricula;
        
        protected global::System.Web.UI.WebControls.TextBox txtMatricula;
        
        protected global::System.Web.UI.WebControls.Button btnVerificar;
        
        protected global::System.Web.UI.WebControls.Panel panelVerificar;
        
        protected global::System.Web.UI.WebControls.TextBox txtVerificacaoNome;
        
        protected global::System.Web.UI.WebControls.TextBox txtVerificacaoCPF;
        
        protected global::System.Web.UI.WebControls.TextBox txtVerificacaoMatricula;
        
        protected global::System.Web.UI.WebControls.TextBox txtVerificacaoNascimento;
        
        protected global::System.Web.UI.WebControls.TextBox txtVerificacaoEmail;
        
        protected global::System.Web.UI.WebControls.TextBox txtSenhaConfirmacao;
        
        protected global::System.Web.UI.WebControls.Button btnAutenticar;
        
        protected global::System.Web.UI.WebControls.Button btnCancelarAutenticacao;
        
        protected global::System.Web.UI.WebControls.Panel panelConfirmarFrequencia;
        
        protected global::System.Web.UI.WebControls.GridView gvFrequencia;
        
        protected global::System.Web.UI.WebControls.Button btnRegistrarFrequencia;
        
        protected global::System.Web.UI.WebControls.Button btnCancelar;
    }
}
